/* 
 * Ojasvita Custom Service Worker
 * Handled by vite-plugin-pwa injectManifest
 */

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkOnly, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

// Clean up old caches automatically
cleanupOutdatedCaches();

// This injects the precache manifest generated by Vite during the build process
precacheAndRoute(self.__WB_MANIFEST || []);

// Safe caching strategy: DO NOT cache API calls
registerRoute(
  ({ url }) => url.href.includes('ojasvita-production.up.railway.app/api'),
  new NetworkOnly()
);

// Cache images
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// --- PUSH NOTIFICATIONS ---

// Event listener for push notifications
self.addEventListener('push', (event) => {
  let data = { title: "Ojasvita Notification", body: "You have a new alert!" };

  try {
    if (event.data) {
      data = event.data.json();
    }
  } catch (error) {
    // If not JSON, try as plain text
    if (event.data) {
      data.body = event.data.text();
    }
  }

  const options = {
    body: data.body,
    icon: '/logo.png',
    badge: '/logo.png',
    data: data.data || {},
    vibrate: [100, 50, 100],
  };

  event.waitUntil(
    self.registration.showNotification(data.title, options)
  );
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  // Focus or open the app window
  event.waitUntil(
    clients.matchAll({ type: 'window' }).then((clientList) => {
      for (const client of clientList) {
        if (client.url && 'focus' in client) {
          return client.focus();
        }
      }
      if (clients.openWindow) {
        return clients.openWindow('/');
      }
    })
  );
});
